/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Hello_constants.h"

namespace HelloThrift { namespace Interface {

const HelloConstants g_Hello_constants;

HelloConstants::HelloConstants() {
}

}} // namespace

